I'm sorry, but an uncaught exception occurred.

After initialization, but before game start.
  File "game/screens.rpy", line 677, in prepare_screen
    screen save():
  File "game/screens.rpy", line 677, in prepare
    screen save():
Exception: A screen named file_slots does not exist.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "C:\Users\LENOVO\Desktop\Study related\Renpy\renpy-8.3.4-sdk\renpy\bootstrap.py", line 359, in bootstrap
    renpy.main.main()
  File "C:\Users\LENOVO\Desktop\Study related\Renpy\renpy-8.3.4-sdk\renpy\main.py", line 652, in main
    run(restart)
  File "C:\Users\LENOVO\Desktop\Study related\Renpy\renpy-8.3.4-sdk\renpy\main.py", line 94, in run
    renpy.display.screen.prepare_screens()
  File "C:\Users\LENOVO\Desktop\Study related\Renpy\renpy-8.3.4-sdk\renpy\display\screen.py", line 1024, in prepare_screens
    s.ast.prepare_screen()
  File "game/screens.rpy", line 677, in prepare_screen
    screen save():
  File "game/screens.rpy", line 677, in prepare
    screen save():
  File "C:\Users\LENOVO\Desktop\Study related\Renpy\renpy-8.3.4-sdk\renpy\sl2\slast.py", line 2030, in prepare
    raise Exception("A screen named {} does not exist.".format(self.target))
Exception: A screen named file_slots does not exist.

Windows-10-10.0.26100 AMD64
Ren'Py 8.3.4.24120703
Alchemi 1.0
Thu Mar 13 07:23:15 2025
